<div class="category"><a href="/">Domov </a> <i class="fa fa-angle-double-right"></i><a href="/kategoria/<?= $article['category'] ?>"> <?= $category ?> </a> </div>

<div id="article-box">
    <h1><?= $article['title'] ?></h1>

    <?= $article['content'] ?>
    <p><?= $article['status'] ?> <?= date("j.n.Y", $article['date']) ?></p>
    Autor: <a href="/uzivatelia/<?= $article['author'] ?>"><?= $article['author'] ?></a>
</div>

<div id="comments-box">
    <h3>Komentáre</h3>

    <?php foreach($comments as $comment) : ?>
        <div class="comment-block">
            <div class="user">
                <img class="commentAvatar" src="/<?= $comment['avatar'] ?>" alt=""><br>
                <strong><a href="/uzivatelia/<?= $comment['author'] ?>"><?= $comment['author'] ?></a></strong><br>
                <?= $comment['userRank'] ?>
            </div>
            <div class="comment">
                <?= $comment['comment'] ?><br>
            </div>
            <div class="comment-date">
               <?= date("j.n.Y H:i", $comment['date']) ?>
               <?php if($admin == 1) : ?>
                    <a href="/clanky/<?= $article['url'] ?>/odstranit-komentar/<?= $comment['comment_id'] ?>"
                       onclick="return confirm('Naozaj chcete odstrániť komentár?');"
                       title="Odstrániť komentár">
                    <i class="fa fa-trash-o fa-fw fa-2x"></i></a>
                <?php endif ?>
            </div>

            <div class="clear"></div>
        </div>
    <?php endforeach ?>
</div>

<?php if(isset($admin)) { //ak je uzivatel prihlaseny ?>

    <section>
        <h4>Pridať komentár</h4>
        <form action="#" method="post">
            <input type="text" name="article_id" value="<?= $article['article_id'] ?>" hidden>
            <input type="text" name="captchaNumber1" value="<?= $captcha['number1'] ?>" hidden>
            <input type="text" name="captchaNumber2" value="<?= $captcha['number2'] ?>" hidden>
            <input type="text" name="author" value="<?= $user ?>" hidden>
            <p> <i><?= $captcha['captcha'] ?></i> <input type="text" name="captchaAnswer" required> </p>
            <textarea name="comment"><?php if(isset($_POST['comment'])) echo(htmlspecialchars($_POST['comment'])) ?></textarea><br>

            <p>
                <img src="/img/smiles/big-smile.gif" title=":D" alt="big smile">
                <img src="/img/smiles/smile.gif" title=":)" alt="smile">
                <img src="/img/smiles/wink.gif" title=";)" alt="wink">
                <img src="/img/smiles/sad.gif" title=":(" alt="sad">
                <img src="/img/smiles/surprised.gif" title=":o" alt="surprised">
            </p>

            <input type="submit" value="Odoslať komentár">
        </form>
    </section>

<?php } else { //ak nie je uzivatel prihlaseny ?>
    <p>Pre zapojenie sa do diskusie musíte byť <a href="/prihlasenie">prihlasený</a>.</p>
<?php } ?>
