<p class="category">Kategória -><a href="/kategoria/<?= $article['category'] ?>"> <?= $category ?> </a> </p>

<header>
    <h1><?= $article['title'] ?></h1>
</header>

<section>
    <?= $article['content'] ?>
    <p><?= $article['status'] ?> <?= date("j.n.Y", $article['date']) ?></p>
    Autor: <a href="/uzivatelia/<?= $article['author'] ?>"><?= $article['author'] ?></a>
</section>

<section>
    <p><strong>Komentáre</strong></p>

    <?php foreach($comments as $comment) : ?>
        <div class="comment-block">
            <div class="user">
                <img id="commentAvatar" src="/img/users/<?= $comment['avatar'] ?>"><br>
                <strong><a href="/uzivatelia/<?= $comment['author'] ?>"><?= $comment['author'] ?></a></strong><br>
                <?= $comment['userRank'] ?>
            </div>
            <div class="comment">
                <?= $comment['comment'] ?><br>
            </div>
            <div class="comment-date">
               <?= date("j.n.Y H:i", $comment['date']) ?>
               <?php if(isset($admin)) : ?>
                    <a href="/clanky/<?= $article['url'] ?>/odstranit-komentar/<?= $comment['comment_id'] ?>"
                       onclick="return confirm('Naozaj chcete odstrániť komentár?');"
                       title="Odstrániť komentár">
                    <i class="fa fa-trash-o fa-fw fa-2x"></i></a>
                <?php endif ?>
            </div>

            <div class="clear"></div>
        </div>
    <?php endforeach ?>
</section>

<?php if(isset($admin)) { //ak je uzivatel prihlaseny ?>

    <section>
        <h3>Pridať komentár</h3>
        <form action="#" method="post">
            <input type="text" name="article_id" value="<?= $article['article_id'] ?>" hidden>
            <input type="text" name="author" value="<?= $user ?>" hidden>
            <input type="text" name="year" placeholder="Antispam - zadajte aktuálny rok" required>
            <textarea name="comment"><?php if(isset($_POST['comment'])) echo(htmlspecialchars($_POST['comment'])) ?></textarea><br>
            <input type="submit" value="Odoslať komentár">
        </form>
    </section>

<?php } else { //ak nie je uzivatel prihlaseny ?>
    <p>Pre zapojenie sa do diskusie musíte byť <a href="/prihlasenie">prihlasený</a>.</p>
<?php } ?>
