<div class="category"><a href="/">Domov </a> <i class="fa fa-angle-double-right"></i><a href="/kategoria/<?= $article['category'] ?>"> <?= $category ?> </a> </div>

<div id="article-box">
    <h1><?= $article['title'] ?></h1>

    <?= $article['content'] ?>
    <div class="article-bottom">
        <?= $article['status'] ?> <?= date("j.n.Y", $article['date']) ?><br>
        Autor: <a href="/uzivatelia/<?= $article['author'] ?>"><?= $article['author'] ?></a>
    </div>
</div>

<div id="comments-box">
    <h3>Komentáre</h3>

    <?php foreach($comments as $comment) : ?>
        <div class="comment-block">
            <div class="user">
                <img class="commentAvatar" src="/<?= $comment['avatar'] ?>" alt=""><br>
                <strong><a href="/uzivatelia/<?= $comment['author'] ?>"><?= $comment['author'] ?></a></strong><br>
                <?= $comment['userRank'] ?>
            </div>
            <div class="comment">
                <?= $comment['comment'] ?><br>
            </div>
            <div class="comment-date">
               <?= date("j.n.Y H:i", $comment['date']) ?>
               <?php if($admin == 1) : ?>
                    <a href="/clanky/<?= $article['url'] ?>/odstranit-komentar/<?= $comment['comment_id'] ?>"
                       onclick="return confirm('Naozaj chcete odstrániť komentár?');"
                       title="Odstrániť komentár">
                    <i class="fa fa-trash-o fa-fw fa-2x"></i></a>
                <?php endif ?>
            </div>

            <div class="clear"></div>
        </div>
    <?php endforeach ?>
</div>

<?php if(isset($admin)) { //ak je uzivatel prihlaseny ?>

    <section class="box">
        <form action="#" method="post">
            <input type="hidden" name="article_id" value="<?= $article['article_id'] ?>" >
            <input type="hidden" name="captchaNumber1" value="<?= $captcha['number1'] ?>" >
            <input type="hidden" name="captchaNumber2" value="<?= $captcha['number2'] ?>" >
            <input type="hidden" name="author" value="<?= $user ?>" >

            <div class="responsive-commentForm">
                <span class="label">Pridať komentár</span>
                <textarea name="comment" id="commentTextarea"><?php if(isset($_POST['comment'])) echo(htmlspecialchars($_POST['comment'])) ?></textarea><br>

                <div id="emoticons">
                    <span title=":D"><img src="/img/smiles/big-smile.gif" alt=":D"></span>
                    <span title=":)"><img src="/img/smiles/smile.gif" alt=":)"></span>
                    <span title=";)"><img src="/img/smiles/wink.gif" alt=";)"></span>
                    <span title=":("><img src="/img/smiles/sad.gif" alt=":("></span>
                    <span title=":o"><img src="/img/smiles/surprised.gif" alt=":o"></span>
                </div>
            </div>

            <div class="captcha-box">
            <span>
                Ochrana proti spamu. Napíš výsledok číslom<br><i><?= $captcha['captcha'] ?></i>
                <input type="text" name="captchaAnswer" required>
            </span>
            </div>

            <input type="submit" value="Odoslať komentár">
        </form>
    </section>

<?php } else { //ak nie je uzivatel prihlaseny ?>
    <p>Pre zapojenie sa do diskusie musíte byť <a href="/prihlasenie">prihlasený</a>.</p>
<?php } ?>


<!-- Javascript (emoticons) -->
<script>
    $('#emoticons span').click(function() {
        var smiley = $(this).attr('title');
        ins2pos(smiley, 'commentTextarea');
    });

    function ins2pos(str, id) {
        var TextArea = document.getElementById(id);
        var val = TextArea.value;
        var before = val.substring(0, TextArea.selectionStart);
        var after = val.substring(TextArea.selectionEnd, val.length);
        TextArea.value = before + str + after;
    }
</script>
