<h1> <?= $category ?> </h1>

<?php $articleCounter = 0; #pocitadlo clankov (maximalne 5 clankov na 1 strane) ?>
<?php foreach ($articles as $article) : ?>

<?php
        $articleCounter++;
        if($articleCounter <= 5) : ?>
                <?php if(($article['public'] == '1') || (($article['public'] == '0') && ($admin == '1'))) : #Ak je clanok publikovany ALEBO je prihlaseny admin A clanok nie je publikovany ?>

                    <div class="articleList-box">
                        <h2 class="articleList-title"><a href="/clanky/<?= $article['url'] ?>"><?= $article['title'] ?></a></h2>
                        <div class="articleList-heading">
                            <i class="fa fa-calendar"></i> <?= date("j.n.Y", $article['date']) ?>
                            <i class="fa fa-user"></i> <?= $article['author'] ?><br>
                        </div>

                        <div class="articleList-container">
                            <a href="/clanky/<?= $article['url'] ?>"><img src="/<?= $article['thumbnail_img'] ?>" alt=""></a>
                            <span class="articleList-text"><?= $article['description'] ?></span>
                        </div>
                        <div class="clear"></div>

                        <?php if($admin == '1') : //ak je prihlaseny admin ?>
                            <div class="articleList-bottom">
                                <?= $article['status'] ?>
                                <a href="/editor/<?= $article['url'] ?>"><i class="fa fa-pencil fa-fw"></i> Editovať </a>
                                <a href="/clanky/<?= $article['url'] ?>/odstranit"
                                   onclick="return confirm('Naozaj chcete odstrániť článok?');"><i class="fa fa-trash-o fa-fw"></i>Odstrániť
                                </a>
                            </div>
                        <?php endif ?>
                    </div>
                    <div class="clear"></div>
                <?php endif ?>
        <?php endif ?>

<?php endforeach ?>

<?php if(isset($pages)) : ?>
    <p class="pages">
        <?php
            for($i = 1; $i <= $pages; $i++) {
                if($i == $currentPage)
                    echo " <strong><a href='/kategoria/" . $category . "/page/" . $i . "'>" . $i . "</a></strong> ";
                else
                    echo " <a href='/kategoria/" . $category . "/page/" . $i . "'>" . $i . "</a> ";
            }
        ?>
    </p>
<?php endif ?>
