<h1>Ovládací panel</h1>
<br>

<?php if($admin == '1') : #ak je prihlaseny admin ?>

    <fieldset>
        <legend>Možnosti</legend>
        <p><a href="/editor"><i class="fa fa-pencil"></i> Nový článok</a></p>
        <p><a href="/clanky/unpublished"><i class="fa fa-pencil-square-o"></i> Rozpísané články</a></p>
        <p><a href="/clanky"><i class="fa fa-tasks"></i> Správa článkov</a></p>
        <p><a href="/uzivatelia"><i class="fa fa-users"></i> Správa užívatelov</a></p>
        <p><a href="/statistiky"><i class="fa fa-bar-chart"></i> Štatistiky</a></p>
        <p><a href="/uzivatelia/<?= $user ?>"><i class="fa fa-cog fa-fw"></i> Nastavenia profilu</a></p>
    </fieldset>


    <fieldset>
        <legend>Oznamy</legend>
        <table>
            <?php foreach($notices as $notice) : ?>
                <tr>
                    <td><?= $notice['notice'] ?></td>
                    <td><?= $notice['type'] ?></td>
                    <td>
                        <a href="/panel/<?= $notice['notice_id'] ?>/odstranit"
                            onclick="return confirm('Naozaj chcete odstrániť oznam?');"><i class="fa fa-trash-o fa-fw"></i></a>
                    </td>
                </tr>
            <?php endforeach ?>
        </table>

        <p>
            <form action="" method="post" id="notice-form">
                Nový oznam<br>
                <input type="text" name="noticeField" required>
                <select name="noticeStyle" form="notice-form" required>
                    <option value="info">Info</option>
                    <option value="success">Úspech</option>
                    <option value="warning">Varovanie</option>
                </select>
                <input type="submit" value="Vložiť oznam">
            </form>
        </p>
    </fieldset>

<?php endif ?>

<?php if($admin == '2') : #ak je prihlaseny redaktor ?>

    <fieldset>
        <legend>Možnosti</legend>
        <p><a href="/editor"><i class="fa fa-pencil"></i> Nový článok</a></p>
        <p><a href="/clanky"><i class="fa fa-tasks"></i> Moje články</a></p>
        <p><a href="/uzivatelia/<?= $user ?>"><i class="fa fa-cog fa-fw"></i> Nastavenia profilu</a></p>
    </fieldset>

<?php endif ?>

<fieldset>
    <legend>Správy</legend>
    <p><a href="/sprava/vytvorit"><i class="fa fa-envelope-o"></i> Nová správa</a></p>

    <p>
        <strong>Prijaté</strong>
        <?php if(!empty($receivedMessages)) : ?>
            <table>
                <tr>
                    <th>Čas</th>
                    <th>Od</th>
                    <th>Správa</th>
                </tr>
                <?php foreach($receivedMessages as $message) : ?>
                    <tr>
                        <td><?= date("j.n.Y", $message['date']) ?></td>
                        <td><a href="/uzivatelia/<?= $message['sender'] ?>"><?= $message['sender'] ?></a></td>
                        <td><a href="/sprava/<?= $message['message_id'] ?>/zobrazit"><?= $message['message'] ?></a></td>
                        <td>
                            <a href="/sprava/<?= $message['message_id'] ?>/odstranit"
                               onclick="return confirm('Naozaj chcete odstrániť správu?');"><i class="fa fa-trash-o fa-fw"></i></a>
                        </td>
                    </tr>
                <?php endforeach ?>
            </table>
        <?php else: ?>
            <p><i>Žiadne prijaté správy</i></p>
        <?php endif ?>
    </p>

    <p>
        <strong>Odoslané</strong>
        <?php if(!empty($sentMessages)) : ?>
            <table>
                <tr>
                    <th>Čas</th>
                    <th>Komu</th>
                    <th>Správa</th>
                </tr>
                <?php foreach($sentMessages as $message) : ?>
                    <tr>
                        <td><i><?= date("j.n.Y", $message['date']) ?><i/></td>
                        <td><a href="/uzivatelia/<?= $message['recipient'] ?>"><?= $message['recipient'] ?></a></td>
                        <td><a href="/sprava/<?= $message['message_id'] ?>/zobrazit"><?= $message['message'] ?></a></td>
                        <td>
                            <a href="/sprava/<?= $message['message_id'] ?>/odstranit"
                               onclick="return confirm('Naozaj chcete odstrániť správu?');"><i class="fa fa-trash-o fa-fw"></i></a>
                        </td>
                    </tr>
                <?php endforeach ?>
            </table>
        <?php else: ?>
            <p><i>Žiadne odoslané správy</i></p>
        <?php endif ?>
    </p>

</fieldset>
