<div class="category"><a href="/">Domov </a></div>


<?php if($admin == '1') : #ak je prihlaseny admin ?>

    <h1>Administračný panel</h1>

    <div class="controlPanelMenu-box">
        <h2 class="controlPanel-title">MENU</h2>

        <div class="controlPanelItem-box">
            <a href="/editor">
                <div class="controlPanelMenu-icon"><i class="fa fa-pencil fa-4x"></i></div>
                <div class="controlPanelMenu-label">Nový článok</div>
            </a>
        </div>

        <div class="controlPanelItem-box">
            <a href="/clanky/unpublished">
                <div class="controlPanelMenu-icon"><i class="fa fa-pencil-square-o fa-4x"></i></div>
                <div class="controlPanelMenu-label">Rozpísané články</div>
            </a>
        </div>

        <div class="controlPanelItem-box">
            <a href="/panel/moje-clanky">
                <div class="controlPanelMenu-icon"><i class="fa fa-pencil-square-o fa-4x"></i></div>
                <div class="controlPanelMenu-label">Moje články</div>
            </a>
        </div>


        <div class="controlPanelItem-box">
            <a href="/clanky">
                <div class="controlPanelMenu-icon"><i class="fa fa-tasks fa-4x"></i></div>
                <div class="controlPanelMenu-label">Správa článkov</div>
            </a>
        </div>

        <div class="controlPanelItem-box">
            <a href="/uzivatelia">
                <div class="controlPanelMenu-icon"><i class="fa fa-users fa-4x"></i></div>
                <div class="controlPanelMenu-label">Správa užívatelov</div>
            </a>
        </div>

        <div class="controlPanelItem-box">
            <a href="/statistiky">
                <div class="controlPanelMenu-icon"><i class="fa fa-bar-chart fa-4x"></i></div>
                <div class="controlPanelMenu-label">Štatistiky</div>
            </a>
        </div>

        <div class="controlPanelItem-box">
            <a href="/uzivatelia/<?= $user ?>">
                <div class="controlPanelMenu-icon"><i class="fa fa-cog fa-fw fa-4x"></i></div>
                <div class="controlPanelMenu-label">Nastavenia profilu</div>
            </a>
        </div>
    </div>


    <div class="controlPanelNotice-box">
        <h2 class="controlPanel-title">OZNAMY</h2>
        <table class="controlPanelNotice-table">
            <?php foreach($notices as $notice) : ?>
                <tr>
                    <td><?= $notice['notice'] ?></td>
                    <td>
                        <a href="/panel/<?= $notice['notice_id'] ?>/odstranit"
                           onclick="return confirm('Naozaj chcete odstrániť oznam?');"><i class="fa fa-trash-o fa-fw fa-2x"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach ?>
        </table>

        <p>
            <form action="" method="post" id="notice-form">
                <input type="text" name="noticeField" placeholder="Nový oznam" required>
                <input type="submit" name="newNoticeSubmit" value="Vložiť oznam">
            </form>
        </p>
    </div>

<?php endif ?>


<?php if($admin == '2') : #ak je prihlaseny redaktor ?>

    <h1>Panel redaktora</h1>

    <div class="controlPanelMenu-box">
        <h2 class="controlPanel-title">MENU</h2>

        <div class="controlPanelItem-box">
            <a href="/editor">
                <div class="controlPanelMenu-icon"><i class="fa fa-pencil fa-4x"></i></div>
                <div class="controlPanelMenu-label">Nový článok</div>
            </a>
        </div>

        <div class="controlPanelItem-box">
            <a href="/panel/moje-clanky">
                <div class="controlPanelMenu-icon"><i class="fa fa-pencil-square-o fa-4x"></i></div>
                <div class="controlPanelMenu-label">Moje články</div>
            </a>
        </div>

        <div class="controlPanelItem-box">
            <a href="/uzivatelia/<?= $user ?>">
                <div class="controlPanelMenu-icon"><i class="fa fa-cog fa-fw fa-4x"></i></div>
                <div class="controlPanelMenu-label">Nastavenia profilu</div>
            </a>
        </div>
    </div>

<?php endif ?>


<?php if($admin == '0') : #ak je prihlaseny clen ?>

    <h1>Užívateľský panel</h1>

    <div class="controlPanelMenu-box">
        <h2 class="controlPanel-title">MENU</h2>

        <div class="controlPanelItem-box">
            <a href="/clanky">
                <div class="controlPanelMenu-icon"><i class="fa fa-tasks fa-4x"></i></div>
                <div class="controlPanelMenu-label">Články</div>
            </a>
        </div>

        <div class="controlPanelItem-box">
            <a href="/uzivatelia/<?= $user ?>">
                <div class="controlPanelMenu-icon"><i class="fa fa-cog fa-fw fa-4x"></i></div>
                <div class="controlPanelMenu-label">Nastavenia profilu</div>
            </a>
        </div>
    </div>

<?php endif ?>


<div class="controlPanelMessage-box">
    <h2 class="controlPanel-title">SPRÁVY</h2>

    <span class="controlPanelMessage-button"><a href="/sprava/vytvorit"><i class="fa fa-envelope-o"></i> Nová správa</a></span>
    <span class="controlPanelMessage-button" id="showReceived">Prijaté</span>
    <span class="controlPanelMessage-button" id="showSended">Odoslané</span>

    <div class="receivedMessages-box">
        <?php if(!empty($receivedMessages)) : ?>
            <table class="messagesTable-list">
                <tr>
                    <th></th>
                    <th>OD</th>
                    <th>PREDMET</th>
                    <th><i class="fa fa-clock-o"></i></th>

                </tr>
                <?php foreach($receivedMessages as $message) : ?>
                    <tr>
                        <td>
                            <a href="/sprava/<?= $message['message_id'] ?>/odstranit"
                               onclick="return confirm('Naozaj chcete odstrániť správu?');" title="Odstrániť"><i class="fa fa-trash-o fa-fw fa-2x"></i></a>
                        </td>
                        <td><a href="/uzivatelia/<?= $message['sender'] ?>"><?= $message['sender'] ?></a></td>

                        <?php if($message['unread'] == 1) : #ak je sprava neprecitana, zobraz ju tucnym pismom ?>
                            <td><a href="/sprava/<?= $message['message_id'] ?>/zobrazit"><strong><?= $message['subject'] ?></strong></a></td>
                        <?php else : #ak je sprava precitana ?>
                            <td><a href="/sprava/<?= $message['message_id'] ?>/zobrazit"><?= $message['subject'] ?></a></td>
                        <?php endif ?>

                        <td><?= date("j.n.Y", $message['date']) ?></td>
                    </tr>
                <?php endforeach ?>
            </table>

        <?php else: ?>
            <p><i>Žiadne prijaté správy</i></p>
        <?php endif ?>
    </div>


    <div class="sendedMessages-box">
        <?php if(!empty($sentMessages)) : ?>
            <table class="messagesTable-list">
                <tr>
                    <th></th>
                    <th>KOMU</th>
                    <th>PREDMET</th>
                    <th><i class="fa fa-clock-o"></i></th>
                </tr>
                <?php foreach($sentMessages as $message) : ?>
                    <tr>
                        <td>
                            <a href="/sprava/<?= $message['message_id'] ?>/odstranit"
                               onclick="return confirm('Naozaj chcete odstrániť správu?');"><i class="fa fa-trash-o fa-fw fa-2x"></i></a>
                        </td>
                        <td><a href="/uzivatelia/<?= $message['recipient'] ?>"><?= $message['recipient'] ?></a></td>
                        <td><a href="/sprava/<?= $message['message_id'] ?>/zobrazit"><?= $message['subject'] ?></a></td>
                        <td><i><?= date("j.n.Y", $message['date']) ?><i/></td>
                    </tr>
                <?php endforeach ?>
            </table>
        <?php else: ?>
            <p><i>Žiadne odoslané správy</i></p>
        <?php endif ?>
    </div>
</div>


<!-- Javascript -->
<script>
    $("#showReceived").click(function(){
        $(".receivedMessages-box").toggle(180);
        $(".sendedMessages-box").hide(180);
        $("#showReceived").toggleClass("activeButton");
        $("#showSended").removeClass("activeButton");
    });

    $("#showSended").click(function(){
        $(".sendedMessages-box").toggle(180);
        $(".receivedMessages-box").hide(180);
        $("#showSended").toggleClass("activeButton");
        $("#showReceived").removeClass("activeButton");
    });
</script>
