<div class="category"><a href="/">Domov </a></div>

<form method="post" action="#">

    <input type="hidden" name="captchaNumber1" value="<?= $captcha['number1'] ?>" >
    <input type="hidden" name="captchaNumber2" value="<?= $captcha['number2'] ?>" >

    <h1>Kontaktujte nás</h1>

    <div class="responsive-form">
        <span>Vaša emailová adresa</span>
        <input type="email" name="email" value="<?= $email ?>" required>
        <span>Vaša správa</span>
        <textarea name="message"><?= $message ?></textarea>
    </div>

    <div class="captcha-box">
            <span>
                Ochrana proti spamu. Napíš výsledok číslom<br><i><?= $captcha['captcha'] ?></i>
                <input type="text" name="captchaAnswer" required>
            </span>
    </div>
    <input type="submit" value="Odoslať">
</form>