<h1>Ovládací panel</h1>
<br>

<?php if($admin == '1') : #ak je prihlaseny admin ?>

    <ul>
        <li><a href="/editor"><i class="fa fa-pencil"></i> Nový článok</a></li>
        <li><a href="/clanky/unpublished"><i class="fa fa-pencil-square-o"></i> Rozpísané články</a></li>
        <li><a href="/clanky"><i class="fa fa-tasks"></i> Správa článkov</a></li>
        <li><a href="/uzivatelia"><i class="fa fa-users"></i> Správa užívatelov</a></li>
        <li><a href="/statistiky"><i class="fa fa-bar-chart"></i> Štatistiky</a></li>
    </ul>


    <h2>Oznamy</h2>
    <table>
        <?php foreach($notices as $notice) : ?>
            <tr>
                <td><?= $notice['notice'] ?></td>
                <td><?= $notice['type'] ?></td>
                <td>
                    <a href="/panel/<?= $notice['notice_id'] ?>/odstranit"
                        onclick="return confirm('Naozaj chcete odstrániť oznam?');"><i class="fa fa-trash-o fa-fw"></i></a>
                </td>
            </tr>
        <?php endforeach ?>
    </table>

    <p>
        <form action="" method="post" id="notice-form">
            Nový oznam
            <input type="text" name="noticeField" required>
            <select name="noticeStyle" form="notice-form" required>
                <option value="info">Info</option>
                <option value="success">Úspech</option>
                <option value="warning">Varovanie</option>
            </select>
            <input type="submit" value="Vložiť oznam">
        </form>
    </p>

<?php endif ?>

<?php if($admin == '2') : #ak je prihlaseny redaktor ?>

    <ul>
        <li><a href="/editor"><i class="fa fa-pencil"></i> Nový článok</a></li>
        <li><a href="/clanky"><i class="fa fa-tasks"></i> Moje články</a></li>
    </ul>

<?php endif ?>

<h2>Správy</h2>
<table>
    <tr>
        <td>Prijaté</td>
        <td>Odoslané</td>
    </tr>
</table>

<h2><?= $user ?></h2>
<h3>Prehľad profilu</h3>
<br>

<table>
    <tr>
        <td><img id="avatar" src="/<?= $avatar ?>"></td>
    </tr>

    <tr>
        <td>Hodnosť</td>
        <td><?= $userRank ?></td>
    </tr>

    <tr>
        <td>Registrovaný</td>
        <td><?= date("j.n.Y H:i:s", $registrationDate) ?></td>
    </tr>

    <tr>
        <td>Posledné prihlásenie</td>
        <td><?= date("j.n.Y H:i:s", $lastVisit) ?></td>
    </tr>

    <tr>
        <td>Článkov</td>
        <td><?= $articles ?></td>
    </tr>

    <tr>
        <td>Komentárov</td>
        <td><?= $comments ?></td>
    </tr>

    <tr>
        <td>Pohlavie</td>
        <td><?= $sex ?></td>
    </tr>

    <tr>
        <td>Email</td>
        <td><?= $email ?></td>
    </tr>
</table>
<br>
<a href="/uzivatelia/<?= $user ?>"><i class="fa fa-cog fa-fw"></i> Nastavenia profilu</a>
