<div class="category"><a href="/">Domov </a></div>

<h1>Editor článkov</h1>

<form action="" method="post" id="editor-form" enctype="multipart/form-data">
    <input type="hidden" name="article_id" value="<?= $article['article_id'] ?>">
    <input type="hidden" name="author" value="<?= $article['author'] ?>">
    <input type="hidden" name="url" value="<?= $article['url'] ?>">

    <table>

        <tr>
            <td>Kategória</td>
            <td>
                <select name="category" form="editor-form" required>
                    <option value="novinky" <?php if($article['category'] == 'novinky') echo 'selected'; ?> >Novinky</option>
                    <option value="programovanie" <?php if($article['category'] == 'programovanie') echo 'selected'; ?> >Programovanie</option>
                    <option value="hardware" <?php if($article['category'] == 'hardware') echo 'selected'; ?> >Hardware</option>
                    <option value="software" <?php if($article['category'] == 'software') echo 'selected'; ?> >Software</option>
                    <option value="ostatne" <?php if($article['category'] == 'ostatne') echo 'selected'; ?> >Ostatné</option>
                </select>
            </td>
        </tr>

        <tr>
            <td>Titulok</td>
            <td><input type="text" name="title" value="<?= $article['title'] ?>" required></td>
        </tr>

        <tr>
            <td>Popis</td>
            <td><input type="text" name="description" value="<?= $article['description'] ?>" required></td>
        </tr>

        <tr>
            <td>Kľučové slová</td>
            <td><input type="text" name="key_words" value="<?= $article['key_words'] ?>" required><br></td>
        </tr>

        <tr>
            <td>Náhľadový obrázok</td>
            <td>
                <i class="fa fa-upload"></i>
                <input type="file" size="32" name="image_field">
            </td>
        </tr>

    </table>
    <br>

    <textarea name="content"><?= $article['content'] ?></textarea><br>
    <input type="submit" value="Uložiť článok">
</form>


<script type="text/javascript" src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea[name=content]",
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste"
        ],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
        entities: "160,nbsp",
        entity_encoding: "named",
        entity_encoding: "raw"
    });
</script>