<!DOCTYPE html>

<html lang="sk">

<head>
    <!--[if lt IE 9]><script src="js/html5shiv-printshiv.js"></script><![endif]-->
    <title><?= $title ?></title>
    <meta charset="UTF-8"/>
    <meta name="description" content="<?= $description ?>"/>
    <meta name="keywords" content="<?= $key_words ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="/css/style.css" type="text/css">
    <link rel="stylesheet" href="/css/front-page.css" type="text/css">
    <link rel="stylesheet" href="/css/responsive-nav.css" type="text/css">
    <script src="/js/responsive-nav.js"></script>
</head>

<body>

<nav class="nav-collapse">
    <ul>
        <li class="logo"><strong><a href="/"><span class="blue-letter">C</span>oding</a></strong></li>
        <li><a href="/kategoria/novinky">Novinky</a></li>
        <li><a href="/kategoria/programovanie">Programovanie</a></li>
        <li><a href="/kategoria/hardware">Hardware</a></li>
        <li><a href="/kategoria/software">Software</a></li>
        <li><a href="/kategoria/ostatne">Ostatné</a></li>
    </ul>
</nav>

<section>
    <?php foreach($messages as $message) : ?>
        <p class="<?= $message[1] ?>"><?= $message[0] ?></p>
    <?php endforeach ?>
</section>


<div id="content">

    <section class="updates">
        <h1>MVC CMS system <strong>v.1.07</strong></h1>
        <h2>Updates</h2>

        <p>
            <table>
                <tr><th>Features</th><th></th></tr>
                <tr><td>uzivatelsky profil, avatar, pocet komentarov, uzivatelske nastavenia</td><td>✔✔</td></tr>
                <tr><td>komentare k clankom</td><td>✔✔</td></tr>
                <tr><td>nahladove obrazky clankov, defaultny obrazok</td><td>✔✔</td></tr>
                <tr><td>datum pridania clanku, autor clanku</td><td>✔✔</td></tr>
                <tr><td>zobrazenie/skrytie clanku</td><td>✔✔</td></tr>
                <tr><td>pocet clankov uzivatela</td><td>✔✔</td></tr>
                <tr><td>upload vlastneho avataru</td><td>✔✔</td></tr>
                <tr><td>validacia pola URL v editore</td><td>✔✔</td></tr>
                <tr><td>validacia mien uzivatelov pri registracii</td><td>✔✔</td></tr>
                <tr><td>pocet zobrazeni clanku</td><td>✔✔</td></tr>
                <tr><td>vypis clankov rozdeleny na viacere strany</td><td>✔✔</td></tr>
                <tr><td>potvrdzovacie dialogy pre zmazanie</td><td>✔✔</td></tr>
                <tr><td>responzivny dizajn</td><td>✔✔</td></tr>
                <tr><td>kategoriaController pre vypis clankov v danej kategorii</td><td>✔✔</td></tr>
                <tr><td>odstranit ponuku autorov clankov v editore</td><td>✔✔</td></tr>
                <tr><td>zobrazenie cesty k clanku (kategorie)</td><td>✔✔</td></tr>
                <tr><td>upload nahladovych obrazkov clankov</td><td>✔✔</td></tr>
                <tr><td>oznamy</td><td>✔✔</td></tr>
                <tr><td>lepsi antispam pri komentaroch</td><td>✔✔</td></tr>
                <tr><td>sprava uzivatelov - mazanie uctov, zmena opravneni</td><td>✔✔</td></tr>
                <tr><td>smajlici v komentaroch</td><td>✔✔</td></tr>
                <tr><td>avatar prihlaseneho uzivatela na bocnom paneli</td><td>✔✔</td></tr>
                <tr><td>posielanie sprav medzi uzivatelmi</td><td>✔✔</td></tr>
                <tr><td>precitane a neprecitane spravy</td><td>✔✔</td></tr>
                <tr><td>'Moje clanky' v control paneli autorov</td><td>✔✔</td></tr>
                <tr><td>uvodna stranka</td><td>✔-</td></tr>
                <tr><td>dizajn formularov a tabuliek</td><td>-</td></tr>
                <tr><td>osetrenie vsetkych vstupov od uzivatelov</td><td>-</td></tr>
                <tr><td>statistiky navstevnosti, clankov, uzivatelov</td><td>-</td></tr>
                <tr><td>vyhladavanie clankov podla klucovych slov (google engine)</td><td>-</td></tr>
            </table>
        </p>

        <p>
            <table>
                <tr><th>Known bugs</th><th></th></tr>
                <tr><td>zobrazenie viacerych sprav naraz</td><td>fixed ✔✔</td></tr>
                <tr><td>po zmene uzivatelskych nastaveni sa neaktualizuje session</td><td>fixed ✔✔</td></tr>
                <tr><td>pri nahrani avataru s rovnakym menom suboru vypise chybu</td><td>fixed ✔✔</td></tr>
                <tr><td>ak sa vymaze clanok, tak sa neaktualizuje pocet clankov uzivatela</td><td>fixed ✔✔</td></tr>
                <tr><td>ak sa vymaze komentar, tak sa neaktualizuje pocet komentarov uzivatela</td><td>fixed ✔✔</td></tr>
                <tr><td>zmiznutie oznamu ak je v SESSION sprava</td><td>fixed ✔✔</td></tr>
                <tr><td>nefunkcny email formular</td><td>fixed ✔✔</td></tr>

            </table>
        </p>

    </section>

    <footer>
        <p>
            design <strong>&amp;</strong> code | Tomáš Blázy <br>
            &copy;<?= date("Y"); ?> <i>v1.11</i>
            <a href="/kontakt">Kontakt</a> | <a href="/site-map">Mapa stránok</a>
        </p>
    </footer>
</div>

<!-- javascript --------------------------------------------------------------------------->
<script>
    //responsive menu customizable options
    var nav = responsiveNav(".nav-collapse", { // Selector
        animate: true, // Boolean: Use CSS3 transitions, true or false
        transition: 284, // Integer: Speed of the transition, in milliseconds
        label: "<i class='fa fa-bars fa-2x'></i>", // String: Label for the navigation toggle
        insert: "before", // String: Insert the toggle before or after the navigation
        customToggle: "", // Selector: Specify the ID of a custom toggle
        closeOnNavClick: false, // Boolean: Close the navigation when one of the links are clicked
        openPos: "relative", // String: Position of the opened nav, relative or static
        navClass: "nav-collapse", // String: Default CSS class. If changed, you need to edit the CSS too!
        navActiveClass: "js-nav-active", // String: Class that is added to  element when nav is active
        jsClass: "js", // String: 'JS enabled' class which is added to  element
        init: function(){}, // Function: Init callback
        open: function(){}, // Function: Open callback
        close: function(){} // Function: Close callback
    });
</script>

</body>

</html>