<!DOCTYPE html>

<html lang="sk">
    
    <head>
        <title><?= $title ?></title>
        <meta charset="UTF-8"/>
        <meta name="description" content="<?= $description ?>"/>
        <meta name="keywords" content="<?= $key_words ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="stylesheet prefetch" href="http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css">
        <link rel="stylesheet" href="/css/font-awesome.min.css">
        <link rel="stylesheet" href="/css/menu.css" type="text/css">
        <link rel="stylesheet" href="/css/style.css" type="text/css">
    </head>
    
    <body>
        <header>
            <a href="/"><img src="/img/coding-logo.png" alt="coding logo image"></a>
        </header>


        <div id="page">
            <?php foreach($messages as $message) : ?>
                <p class="<?= $message[1] ?>"><?= $message[0] ?></p>
            <?php endforeach ?>

            <a href="#" class="open-panel"><i class="icon-reorder icon-2x"></i></a>

            <nav>
                <a href="#" class="close-panel"><i class="icon-remove-sign icon-2x"></i></a>
                <ul class="menu">
                    <li><a href="/clanky/o-mne">O mne</a></li>
                    <li><a href="/clanky/kategoria1">Kategoria 1</a></li>
                    <li><a href="/clanky/kategoria2">Kategoria 2</a></li>
                    <li><a href="/clanky">Články</a></li>
                    <li><a href="/kontakt">Kontakt</a></li>
                </ul>
            </nav>

            <div id="content">

                <!--Samotny clanok------------------------------------------------------------------------->
                <article>
                    <?=$this->controller->outputView()?>
                </article>

                <!--Bocny panel---------------------------------------------------------------------------->
                <aside>
                    <p><?= $user ?></p>

                    <h2>Najčítanejšie</h2>
                    <ol>
                        <?php foreach($topArticles as $article) : ?>
                            <li><a href="/clanky/<?= $article['url'] ?>"><?= $article['title'] ?></a></li>
                        <?php endforeach ?>
                    </ol>
                </aside>

                <footer>
                    <p>
                        design | code | Tomáš Blázy | &copy; 2015 - <?= date("Y"); ?> <br>
                        <strong>v0.13 | coding.wz.sk</strong>
                    </p>
                </footer>
            </div>
        </div>

        <!-- javascript --------------------------------------------------------------------------->
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="/js/index.js"></script>
        
    </body>

</html>