<!DOCTYPE html>

<html lang="sk">
    <head>
        <!--[if lt IE 9]><script src="js/html5shiv-printshiv.js"></script><![endif]-->
        <title><?= $title ?></title>
        <meta charset="UTF-8"/>
        <meta name="description" content="<?= $description ?>"/>
        <meta name="keywords" content="<?= $key_words ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="/css/style.css">
        <link rel="stylesheet" type="text/css" href="/css/form-style.css">
        <link rel="stylesheet" type="text/css" href="/css/article.css">
        <link rel="stylesheet" type="text/css" href="/css/control-panel.css">
        <link rel="stylesheet" type="text/css" href="/css/responsive-nav.css">
        <script src="/js/responsive-nav.js"></script>

        <!-- jquery core -->
        <script src="//code.jquery.com/jquery-2.2.0.min.js"></script>

        <!-- skripty pre automaticke doplnovanie textovych poli -->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    </head>

    <body>

        <p class="logoMobile"><strong><a href="/"><span class="blue-letter">C</span>oding</a></strong></p>
        <nav class="nav-collapse">
            <ul>
                <li class="logo"><strong><a href="/"><span class="blue-letter">C</span>oding</a></strong></li>
                <li><a href="/kategoria/novinky">Novinky</a></li>
                <li><a href="/kategoria/programovanie">Programovanie</a></li>
                <li><a href="/kategoria/hardware">Hardware</a></li>
                <li><a href="/kategoria/software">Software</a></li>
                <li><a href="/kategoria/ostatne">Ostatné</a></li>
            </ul>
        </nav>

        <div id="messages">
            <?php foreach($messages as $message) : ?>
                <p class="<?= $message[1] ?>"><?= $message[0] ?></p>
            <?php endforeach ?>
        </div>


        <div class="page-wrap">
            <!-- Samotny clanok -->
            <section id="content">
                <?=$this->controller->outputView()?>
            </section>

            <!-- Bocny panel -->
            <aside>
                <div class="loginBox">
                    <span><?= $user ?></span>
                </div>
                <div class="mostReadBox">
                    <h2 class="mostReadBox-title">NAJČÍTANEJŠIE</h2>
                    <ul class="mostReadList">
                        <?php foreach($topArticles as $article) : ?>
                            <li><a href="/clanky/<?= $article['url'] ?>"><?= $article['title'] ?></a></li>
                        <?php endforeach ?>
                    </ul>
                </div>
            </aside>
        </div>

        <footer class="site-footer">
            <p><a href="/kontakt">Kontakt</a> | <a href="/site-map">Mapa stránok</a></p>
            <strong>design &amp; code | Tomáš Blázy <br> &copy; <?= date("Y"); ?></strong>
        </footer>

        <!-- javascript -->
        <script>
            //responsive menu customizable options
            var nav = responsiveNav(".nav-collapse", { // Selector
                animate: true, // Boolean: Use CSS3 transitions, true or false
                transition: 284, // Integer: Speed of the transition, in milliseconds
                label: "<i class='fa fa-bars fa-2x'></i>", // String: Label for the navigation toggle
                insert: "before", // String: Insert the toggle before or after the navigation
                customToggle: "", // Selector: Specify the ID of a custom toggle
                closeOnNavClick: false, // Boolean: Close the navigation when one of the links are clicked
                openPos: "relative", // String: Position of the opened nav, relative or static
                navClass: "nav-collapse", // String: Default CSS class. If changed, you need to edit the CSS too!
                navActiveClass: "js-nav-active", // String: Class that is added to  element when nav is active
                jsClass: "js", // String: 'JS enabled' class which is added to  element
                init: function(){}, // Function: Init callback
                open: function(){}, // Function: Open callback
                close: function(){} // Function: Close callback
            });
        </script>

    </body>

</html>