<div class="category"><a href="/">Domov </a></div>

<h1>Prihlásenie</h1>

<form method="post" action="#">

    <div class="responsive-form">
        <span>Meno</span>
        <input type="text" name="name" required>
        <span>Heslo</span>
        <input type="password" name="password" required>
    </div>

    <input type="submit" value="Prihlásiť">

    <p>Nemáte účet? <a href="registracia">Zaregistrujte sa</a>.</p>
</form>

