<div class="category"><a href="/">Domov </a> <i class="fa fa-angle-double-right"></i><a href="/panel"> Ovládací panel</a> </div>

<h1>Nová správa</h1>

<form action="#" method="post">

    <div class="responsive-form">
        <span>Príjemca</span>
        <input type="text" name="recipient" id="prijemca" value="<?= $recipient_url ?>" required>
        <span>Predmet</span>
        <input type="text" name="subject" required>
        <span>Správa</span>
        <textarea name="message" id="sprava"></textarea>
    </div>

    <input type="submit" name="messageSubmit" value="Odoslať správu">
</form>


<!--autocomplete script-->
<script type="text/javascript">
    $(function() {
        var sourceData = [<?= $autocompleteSource ?>];
        $("#prijemca").autocomplete({
            source: function( request, response ) {
                var matcher = new RegExp( "^" + $.ui.autocomplete.escapeRegex( request.term ), "i" );
                response( $.grep(sourceData, function( item ){
                    return matcher.test( item );
                }) );
            }
        });
    });
</script>
