<fieldset>
    <legend>Správa</legend>
    <p>
        (<i><?= date("j.n.Y H:i", $message['date']) ?></i>)<br>
        Od: <a href="/uzivatelia/<?= $message['sender'] ?>"> <?= $message['sender'] ?></a><br>
        Komu: <a href="/uzivatelia/<?= $message['recipient'] ?>"> <?= $message['recipient'] ?></a><br>
        Predmet: <strong><?= $message['subject'] ?></strong>
    </p>
    <p><?= $message['message'] ?></p>
</fieldset>