<h1>Užívateľský profil</h1>

<?php if($user == $loggedUser['name']) { //zobrazenie nastaveni prihlaseneho uzivatela ?>
    <h3>Nastavenia</h3>
    <p>Tu môžete upraviť nastavenia vášho profilu</p>

    <!-- vlastnost enctype - specifies which content-type to use when submitting the form -->
    <form action="" method="post" enctype="multipart/form-data">
        <h4>Profilový obrázok</h4>
        <img id="avatar" src="/<?= $avatar ?>" alt=""><br><br>
        <i class="fa fa-upload"></i>
        <input type="file" size="32" name="image_field">
        <input type="submit" value="Nahrať obrázok" name="uploadImage">
    </form>

    <form action="" method="post">

         <h4>Pohlavie</h4>
         <input type="radio" name="sex" value="male" <?php if($sex == 'muž') echo('checked'); ?> > Muž<br>
         <input type="radio" name="sex" value="female" <?php if($sex == 'žena') echo('checked'); ?> >Žena

         <h4>Zmena hesla</h4>
         <table>
             <tr>
                 <td>Staré heslo</td>
                 <td><input type="password" name="old"></td>
             </tr>
             <tr>
                 <td>Nové heslo</td>
                 <td><input type="password" name="password"></td>
             </tr>
             <tr>
                 <td>Heslo znovu</td>
                 <td><input type="password" name="password2"></td>
             </tr>
         </table>

         <h4>Zmena e-mailu</h4>
         <i class="fa fa-envelope-o fa-fw"></i><input type="email" name="email" value="<?= $email ?>" placeholder="E-mail">

         <input type="submit" name="submit" value="Uložiť"><br>
         <a href="#"><i class="fa fa-trash"></i> Odstrániť účet</a>

    </form>

<?php } else { //zobrazenie prehladu profilu ineho pouzivatela ?>

    <h2><?= $user ?></h2>

    <table>
        <tr>
            <td><img id="avatar" src="/<?= $avatar ?>" alt=""></td>
            <td></td>
        </tr>

        <tr>
            <td>Hodnosť</td>
            <td><?= $userRank ?></td>
        </tr>

        <tr>
            <td>Články</td>
            <td><?= $articles ?></td>
        </tr>

        <tr>
            <td>Komentáre</td>
            <td><?= $comments ?></td>
        </tr>

        <tr>
            <td>Pohlavie</td>
            <td><?= $sex ?></td>
        </tr>

        <?php if(!empty($email)) : //ak uzivatel uviedol email ?>
            <tr>
                <td>Email</td>
                <td><?= $email ?></td>
            </tr>
        <?php endif ?>

        <tr>
            <td>Registrovaný</td>
            <td><?= date("j.n.Y H:i:s", $registrationDate) ?></td>
        </tr>

        <tr>
            <td>Posledné prihlásenie</td>
            <td><?= date("j.n.Y H:i:s", $lastVisit) ?></td>
        </tr>
    </table>
<?php } ?>