<div class="category"><a href="/">Domov </a></div>

<?php if($user == $loggedUser['name']) { //zobrazenie nastaveni prihlaseneho uzivatela ?>
    <h1>Užívateľské nastavenia</h1>

    <!-- vlastnost enctype - specifies which content-type to use when submitting the form -->
    <form action="" method="post" enctype="multipart/form-data">
        <div class="box">
            <div class="responsive-form">
                <h2>Profilový obrázok</h2>
                <span><img id="avatar" src="/<?= $avatar ?>" alt="<?= $loggedUser['name'] ?> profile avatar"></span>
                <i class="fa fa-upload"></i>
                <input type="file" size="32" name="image_field">
            </div>

            <input type="submit" value="Nahrať obrázok" name="uploadImage">
        </div>
    </form>


    <form action="" method="post">
        <div class="responsive-form">
            <div class="box">
                <h2>Pohlavie</h2>
                <span>Muž</span>
                <input type="radio" name="sex" value="male" <?php if($sex == 'muž') echo('checked'); ?> >
                <span>Žena</span>
                <input type="radio" name="sex" value="female" <?php if($sex == 'žena') echo('checked'); ?> >
            </div>

            <div class="box">
                <h2>Zmena hesla</h2>
                <span>Staré heslo</span>
                <input type="password" name="old">

                <span>Nové heslo</span>
                <input type="password" name="password">

                <span>Heslo znovu</span>
                <input type="password" name="password2">
            </div>

            <div class="box">
                <h2>Zmena e-mailu</h2>
                <span><i class="fa fa-envelope-o fa-fw"></i> Email</span>

                <input type="email" name="email" value="<?= $email ?>" placeholder="E-mail" required>
            </div>

            <div class="box">
                <span><a href="#"><i class="fa fa-trash fa-2x"></i> Odstrániť účet</a></span>
            </div>
        </div>

         <input type="submit" name="submit" value="Uložiť nastavenia">
    </form>


<?php } else { //zobrazenie prehladu profilu ineho pouzivatela ?>

    <h1><?= $user ?></h1>

    <div class="center"><img id="avatar" src="/<?= $avatar ?>" alt="<?= $user ?> profile avatar"></div>

    <table class="responsive-table">
        <tr>
            <td>Hodnosť</td>
            <td><?= $userRank ?></td>
        </tr>

        <tr>
            <td>Články</td>
            <td><?= $articles ?></td>
        </tr>

        <tr>
            <td>Komentáre</td>
            <td><?= $comments ?></td>
        </tr>

        <tr>
            <td>Pohlavie</td>
            <td><?= $sex ?></td>
        </tr>

        <tr>
            <td>Registrovaný</td>
            <td><?= date("j.n.Y H:i:s", $registrationDate) ?></td>
        </tr>

        <tr>
            <td>Posledné prihlásenie</td>
            <td><?= date("j.n.Y H:i:s", $lastVisit) ?></td>
        </tr>
    </table>
<?php } ?>