<form method="post">

    <input type="text" name="captchaNumber1" value="<?= $captcha['number1'] ?>" hidden>
    <input type="text" name="captchaNumber2" value="<?= $captcha['number2'] ?>" hidden>

    <fieldset>
        <legend>Registrácia</legend>
        <p><input type="text" name="name" placeholder="Meno" value="<?= $name ?>" required> </p>
        <p><input type="password" name="password" placeholder="Heslo (min. 5 znakov)" required> </p>
        <p><input type="password" name="password2" placeholder="Heslo znova" required> </p>
        <p><input type="email" name="email" placeholder="E-mail (nepovinné)"> </p>
        <p>
            <i><?= $captcha['captcha'] ?></i><br>
            <input type="text" name="captchaAnswer" required>
        </p>
    </fieldset>

    <input type="submit" value="Registrovať">

</form>