<h1>Registrácia</h1>

<form method="post">

    <table>
        <tr>
            <td>Meno</td>
            <td><input type="text" name="name" required></td>
        </tr>

        <tr>
            <td>Heslo</td>
            <td><input type="password" name="password" placeholder="Minimálna dĺžka hesla je 5 znakov" required></td>
        </tr>

        <tr>
            <td>Heslo znova</td>
            <td><input type="password" name="password2" required></td>
        </tr>

        <tr>
            <td>E-mail (nepovinné)</td>
            <td><input type="email" name="email"></td>
        </tr>

        <tr>
            <td>Antispam</td>
            <td><input type="text" name="year" placeholder="zadajte aktuálny rok" required></td>
        </tr>

        <tr>
            <td><input type="submit" value="Registrovať"></td>
        </tr>
    </table>

</form>