<div class="category"><a href="/">Domov </a> <i class="fa fa-angle-double-right"></i><a href="/panel"> Ovládací panel</a> </div>

<h1>Štatistiky</h1>

<h2><a href="//stats.tomasblazy.com">BBClone</a></h2>

<h3>Články podľa návštevnosti</h3>
<table class="responsive-table">
    <tr>
        <th>Článok</th>
        <th>Zobrazenia</th>
    </tr>
    <?php foreach($articlesByVisits as $article) : ?>
        <tr>
            <td><?= $article['title'] ?></td>
            <td><?= $article['visits'] ?></td>
        </tr>
    <?php endforeach ?>
</table>

