<div class="category"><a href="/">Domov </a> <i class="fa fa-angle-double-right"></i><a href="/panel"> Ovládací panel</a> </div>

<h1>Štatistiky</h1>

<div class="controlPanelMenu-box">
    <h2 class="controlPanel-title">MENU</h2>

    <div class="controlPanelItem-box">
        <a href="//stats.tomasblazy.com">
            <div class="controlPanelMenu-icon"><i class="fa fa-area-chart fa-4x"></i></div>
            <div class="controlPanelMenu-label">Kompletné štatistiky</div>
        </a>
    </div>

    <div class="controlPanelItem-box">
        <a href="#" id="article-stats">
            <div class="controlPanelMenu-icon"><i class="fa fa-bar-chart fa-4x"></i></div>
            <div class="controlPanelMenu-label">Články</div>
        </a>
    </div>
</div>


<table class="responsive-table" id="stats-table">
    <tr>
        <th>Článok</th>
        <th>Zobrazenia</th>
    </tr>
    <?php foreach($articlesByVisits as $article) : ?>
        <tr>
            <td><?= $article['title'] ?></td>
            <td><?= $article['visits'] ?></td>
        </tr>
    <?php endforeach ?>
</table>



<!-- Javascript -->
<script>
    $("#article-stats").click(function(){
        $("#stats-table").toggle(200);
    });
</script>

