<h1>Správa užívateľov</h1>

<table>
    <tr>
        <th>Uzivatel</th>
        <th>Hodnosť</th>
        <td></td>
    </tr>
    <?php if($admin) : ?>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td><a href="uzivatelia/<?= $user['name'] ?>"><?= $user['name'] ?></a></td>
                <td><?= $user['rank'] ?></td>

                <?php if($user['name'] != $loggedUser['name']) : #zabranenie odstranenia prihlaseneho uzivatela ?>
                    <td><a href="uzivatelia/<?= $user['name'] ?>/zmenit-opravnenie" title="Zmeniť oprávnenie"
                           onclick="return confirm('Naozaj chcete zmeniť oprávnenie užívateľa?');"><i class="fa fa-user"></i></a>
                    </td>
                    <td><a href="uzivatelia/<?= $user['name'] ?>/odstranit" title="Odstrániť užívateľa"
                           onclick="return confirm('Naozaj chcete odstrániť užívateľa?');"><i class="fa fa-trash-o fa-fw"></i></a>
                    </td>
                <?php endif ?>
            </tr>
        <?php endforeach ?>
    <?php endif ?>
</table>